name: Build - Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - id: pr-tasks
        uses: ./actions/pr-tasks
        with:
          checkbox-tasks: |
            run-unit-report:Run unit report?
            run-hello-world:Run hello world?
            run-skipped-cmd:Run skipped cmd?

      - id: hello-world
        if: ${{ fromJSON(steps.pr-tasks.outputs.tasks).run-hello-world == true }}
        run: |
          echo "hello world"

      - id: unit-report
        if: ${{ fromJSON(steps.pr-tasks.outputs.tasks).run-unit-report == true }}
        uses: ./actions/jest-report
        with:
          results-name: Unit Test Report
          results-json-path: ./example_jest_report.json
          output:
            summary
            pr-comment
            annotations

      - id: skipped-cmd
        if: ${{ fromJSON(steps.pr-tasks.outputs.tasks).run-skipped-cmd == true }}
        run: |
          echo "ran skipped cmd"
          exit 1
