name: Build - Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - id: pr-tasks
        uses: ./actions/pr-tasks
        with:
          checkbox-tasks: |
            run-unit-report:Run unit report?
            run-hello-world:Run hello world?

      - id: hello-world
        run: |
          echo "${{ steps.pr-tasks.outputs.tasks }}"
          echo "pr-tasks outputs: ${{ steps.pr-tasks.outputs.tasks }}"
          echo "Parsed JSON: ${{ fromJSON(steps.pr-tasks.outputs.tasks) }}"
          echo "run-hello-world: ${{ steps.pr-tasks.outputs.tasks['run-hello-world'] }}"
          echo "run-unit-report: ${{ fromJSON(steps.pr-tasks.outputs.tasks).run-unit-report }}"

      - id: unit-report
        if: steps.pr-tasks.outputs.tasks['run-unit-report'] == 'true'
        uses: ./actions/jest-report
        with:
          results-name: Unit Test Report
          results-json-path: ./example_jest_report.json
          output:
            summary
            pr-comment
            annotations

      - id: hello-world-aftera
        if: steps.pr-tasks.outputs.tasks['run-hello-world']
        run: |
          echo "hello world"

      - id: hello-world-afterb
        if: ${{ fromJSON(steps.pr-tasks.outputs.tasks).run-hello-world }}
        run: |
          echo "hello world"

      - id: hello-world-afterc
        if: ${{ fromJSON(steps.pr-tasks.outputs.tasks).run-hello-world == 'true' }}
        run: |
          echo "hello world"

      - id: hello-world-afterd
        if: ${{ fromJSON(steps.pr-tasks.outputs.tasks).run-hello-world == true }}
        run: |
          echo "hello world"